### ISSUE TITLE
Migrate the tool to create Redmine issues for new versions to worldnet-cli

### ISSUE THREAD

**Issue by lpavone** [jbraga/worldnet-cli#1]
We have a Java tool that creates common Redmine issues every time we open a new version, to avoid that manual job. It would be good to add that functionality to this tool to avoid having separate tools to maintain.

**Comment by jbraga** [comment]
Hi Leo,
Great idea! We could implement this as part of the `svn:branch` command (and standalone too).

In my mind that'd be two scenarios when using `svn:branch`:
**Scenario 1: Maintenance (M_*) and roadmap (R_*) branches**
Create the Redmine version and the ticket to receive the commit

**Scenario 2: Release branches (VERSION_*)**
Create resources from Scenario 1 and the extra development process tickets.
Is it possible to create the queries as well?

**Comment by lpavone** [comment]
This is what the tool is doing at the moment: https://redmine.worldnettps.com/redmine/projects/net%20traxion/wiki/Redmine_tool_to_create_template_tasks
we can discuss any other functionality. The branch itself is not created by this tool, only the Redmine issues, but a branch creation is something that can be easily automated as well as there is no conflicts or anything to take care of.

**Comment by jbraga** [comment]
Hi Leo, the CLI already supports branch creation.
Have a look: https://www.npmjs.com/package/worldnet-cli#wn-svnbranch-branch
